language: node_js

node_js:
  - "10"
  - "12"
  - "14"
  - "node"

# Trigger a push build on latest and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - latest
    - /^greenkeeper.*$/

jobs:
  include:
    - stage: docs
      node_js: lts/*
      script:
        - npm run textlint
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: overwriting default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: latest
        script:
          - npm run semantic-release

stages:
  - test
  - docs
  - name: release
    if: branch = latest AND type != pull_request
